package backoffice.bean;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

import com.vaadin.annotations.AutoGenerated;

@Entity
public class Restaurant implements Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	Long id;
	int couverts;
	String nom="";
	
	@OneToOne
	Ville ville;
	
	public Restaurant(){
		
	}
	
	public Restaurant(String string){
		
	}
	
	public String getNom() {
		return nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getCouverts() {
		return couverts;
	}

	public void setCouverts(int couverts) {
		this.couverts = couverts;
	}

	public Ville getVille() {
		return ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}
	
	
	
}
